---
- name: Check if repository file exists
  stat:
    path: "{{ apt_repository_file }}"
  register: apt_repository_file_exists

- name: Remove apt repository file if exists
  file:
    path: "{{ apt_repository_file }}"
    state: absent
  when: apt_repository_file_exists.stat.exists

- name: Download PostgreSQL Pro repository script
  uri:
    url: "{{ postgresql_1c_repo_url }}"
    dest: "{{ repository_file }}"
    mode: '0755'
    creates: /tmp/pgpro-repo-add.sh

- name: Execute repository script
  command: "{{ repository_file }}"
  notify:
    - Remove repository script
    - Update repositories packages

- name: Flushing handlers
  meta: flush_handlers
