---
- name: Change postgres user password
  ansible.builtin.shell: |
    cd /tmp && sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '{{ POSTGRES_PASSWORD }}'"
  changed_when: false

- name: Create app1c user for 1C databases
  ansible.builtin.shell: |
    sudo -u postgres psql -c "CREATE USER {{ APP1C_USER }} WITH LOGIN SUPERUSER CREATEDB CREATEROLE INHERIT REPLICATION BYPASSRLS PASSWORD '{{ APP1C_PASSWORD }}';"
  register: create_user
  changed_when: create_user.rc == 0
  failed_when: create_user.rc != 0 and 'already exists' not in create_user.stderr

- name: Grant privileges to app1c user
  ansible.builtin.shell: |
    sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON ALL DATABASES TO {{ APP1C_USER }};"
    sudo -u postgres psql -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO {{ APP1C_USER }};"
    sudo -u postgres psql -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO {{ APP1C_USER }};"
    sudo -u postgres psql -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON FUNCTIONS TO {{ APP1C_USER }};"
    sudo -u postgres psql -c "ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TYPES TO {{ APP1C_USER }};"
  when: create_user.changed
  notify: Restart PostgreSQL



