---
- name: show_postgres_password
  ansible.builtin.debug:
    msg: "Пароль пользователя postgres: {{ postgres_password }}"

- name: show_1c_app_user_password
  ansible.builtin.debug:
    msg: "Пароль пользователя {{ app_1c_user }}: {{ app_1c_password }}"
